Add bindings to CompileOnDemandLayer
bscarlet/llvm-general pull request #189
Opened 2016-09-20 08:35 UTC by cocreature

This is basically the equivalent of `IRCompileLayer` but it compiles modules lazily.

2016-09-29 20:25 UTC, bscarlet requested changes
Only the minor changes requested. Otherwise looks good.

2016-09-29 20:25 UTC, bscarlet commented on llvm-general/src/LLVM/General/Internal/OrcJIT/IRCompileLayer.hs
> +import           LLVM.General.Prelude
Please don't add whitespace after import like this.
In general, don't add whitespace just to line things up, and attempt to style stuff as in the prexisting code.

2016-09-29 20:47 UTC, cocreature commented on llvm-general/src/LLVM/General/Internal/OrcJIT/IRCompileLayer.hs
> +import           LLVM.General.Prelude
Fixed, sorry for that. I need to figure out how to stop my emacs shortcut for sorting imports from aligning them.

2016-10-20 19:39 UTC, cocreature commented
It’s been 3 weeks since I’ve fixed the issues you mentioned. Could you please merge this or tell me what needs to be changed?

2016-10-20 20:07 UTC, bscarlet commented
Sorry. I've been recovering from a hardware failure at home & that's distracted from a lot of other projects.

2016-10-20 20:08 UTC, merged